on:
  push:
    branches:
      - release

jobs:
  python-release:
    name: Python build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        name: Build for ${{ matrix.os }}

      # Install Nuitka
      - name: Install Nuitka
        run: |
          pip install nuitka
      # Compile Python code with Nuitka
      - name: Compile with Nuitka
        run: |
          python -m nuitka --standalone main.py
      # Upload artifact including the compiled binary and the assets folder in a zip file
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ matrix.os }}-build
          path: |
            main.dist/
            assets/
      # Create a release
      - name: Create release
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref,
              name: `Release ${context.ref}`,
              draft: false,
              prerelease: false
            });
            console.log(response.data);


      
    
    
    
  
