on:
  push:
    branches:
      - release

jobs:
  python-release:
    name: Python build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.9
        name: Build for ${{ matrix.os }}

      # Install Nuitka
      - name: Install Nuitka
        run: |
          pip install nuitka
          pip install pygame
      # Compile Python code with Nuitka
      - name: Compile with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
      # Upload artifact including the compiled binary and the assets folder in a zip file
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ matrix.os }}-build
          path: |
            build/*
            assets/
  
  create-release:
    needs: python-release
    name: Create release for all platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        id: create_release
        with:
          makeLatest: true
          name: Release ${{ github.run_number}}
          tag: build-${{ github.run_number}}
          token: ${{ secrets.GH_PT }}
          body: |
            # Release ${{ github.run_number}}

            ## Changelog

            Find the changelog [here](https://firelop.github.io/NyanBomb/changelog/${{ github.run_number }})

            ## Contributors

            NyanBomb codebase is maintained by:
            - Lilian Marilleau
            - Pierre Guchet
            - Nathanaël Queraud
            
            Made at [St-aubin La Salle](https://www.staubinlasalle.fr/) - 2023
      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-latest-build.zip
          asset_name: Build for ubuntu
          asset_content_type: application/octet-stream



      - uses: actions/download-artifact@v3
        with:
          name: windows-latest-build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-latest-build.zip
          asset_name: Build for windows
          asset_content_type: application/octet-stream




      - uses: actions/download-artifact@v3
        with:
          name: macos-latest-build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-latest-build.zip
          asset_name: Build for MacOS
          asset_content_type: application/octet-stream